- name: variables from inventory
  hosts: local
  connection: local
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "{{ Greeting }}, course is {{ Course }}, duration is {{ Duration }}, trainer is {{ Trainer }}"