- name: variables from inventory
  hosts: frontend
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "Hello i am learning , duration is {{ Duration}}, trainer is {{ Trainer }}"